server:
  address: 127.0.0.1
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'
    url: jdbc:mysql://localhost:3306/close_review?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
